- pyproject.toml
Fixes failing publish workflow due to invalid project classifiers.
> Update project configuration with valid classifiers

- kiota_abstractions/authentication/allowed_hosts_validator.py
Closes step 1 in https://github.com/microsoft/kiota-http-python/issues/81
> Allowed host returns True when no hosts are present.

- CHANGELOG.md
- Makefile
- kiota_abstractions/_version.py
- kiota_abstractions/authentication/__init__.py
- kiota_abstractions/authentication/api_key_authentication_provider.py
- tests/authentication/test_api_key_authentication_provider.py
This is related to https://github.com/microsoft/kiota/issues/1902
fixes #48
> Add an API key authentication provider

- CHANGELOG.md
- kiota_abstractions/_version.py
- kiota_abstractions/request_adapter.py
- kiota_abstractions/store/backing_store_factory_singleton.py
Realated to https://github.com/microsoft/kiota-http-python/issues/80
> feat: add request translator

- CHANGELOG.md
- kiota_abstractions/_version.py
- kiota_abstractions/request_information.py
- requirements-dev.txt
Part of https://github.com/microsoft/kiota/issues/1872
> feat: add tracing support

- CHANGELOG.md
- kiota_abstractions/_version.py
> Chore/release v0.8.2

- CHANGELOG.md
- README.md
- kiota_abstractions/_version.py
- pyproject.toml
Bumps to stable version in readiness for GA
> GA release

- .github/workflows/publish.yml
more information https://docs.opensource.microsoft.com/github/apps/permission-changes/
>  - adds permissions to release workflow

- packages/abstractions/pyproject.toml
- packages/authentication/azure/pyproject.toml
- packages/http/httpx/pyproject.toml
related https://github.com/microsoft/kiota-http-python/issues/409#issuecomment-2411239967
CC @sdarmofal
> fix: bumps required open telemetry version

- README.md
> fix: fix missing plugin on deployment and readme typo

- packages/serialization/multipart/CHANGELOG.md
trigger release in a valid package folder
> fix: fixed deployment and cleanup readmes

- .github/release-please.yml
Adds missing config file for the bot.
> chore: fix missing configuration file

- README.md
This PR addresses several grammar and clarity improvements in the README file, ensuring better readability and understanding. The changes focus on:
- Improving sentence structure for clearer communication.
- Correcting minor grammatical errors.
- Enhancing flow and consistency in the document.
These updates ensure that the README is more user-friendly and easier to comprehend for both new and experienced developers. No code changes have been made; this PR is documentation-only.
> [DOCS] Fix grammar issues in readme.

- .github/workflows/publish.yml
- packages/abstractions/CHANGELOG.md
Follow up to https://github.com/microsoft/kiota-python/pull/376
> fix: fixed missing install command before release

- .github/workflows/publish.yml
- packages/serialization/multipart/CHANGELOG.md
fix: update workflow filter to allow release
> fix: update workflow filter to allow release

- packages/serialization/json/kiota_serialization_json/json_parse_node.py
- packages/serialization/json/tests/helpers/union_type.py
- packages/serialization/json/tests/helpers/user2.py
- packages/serialization/json/tests/unit/conftest.py
- packages/serialization/json/tests/unit/test_intersection_wrapper.py
- packages/serialization/json/tests/unit/test_json_parse_node.py
- packages/serialization/json/tests/unit/test_json_parse_node_factory.py
- packages/serialization/json/tests/unit/test_json_serialization_writer_factory.py
- packages/serialization/json/tests/unit/test_union_wrapper.py
This PR is not needed per se, just some linting related stuff that I noticed while working on something else.
Increases PyLint score slightly.
> remove unused code/imports as well as some reformatting

- .github/dependabot.yml
updates dependabot config for sucessfull updates of packages
> chore: update dependabot config file for updates across projects

- .github/workflows/build.yml
- .github/workflows/publish.yml
- .release-please-manifest.json
- README.md
- packages/bundle/.pylintrc
- packages/bundle/CHANGELOG.md
- packages/bundle/LICENSE
- packages/bundle/README.md
- packages/bundle/kiota_bundle/default_request_adapter.py
- packages/bundle/pyproject.toml
- packages/bundle/tests/test_default_request_adapter.py
- projects-config.json
- release-please-config.json
Fixes https://github.com/microsoft/kiota-python/issues/395
> feat: Add bundle package for python.

- packages/abstractions/kiota_abstractions/request_information.py
- packages/abstractions/pyproject.toml
- packages/abstractions/tests/test_request_information.py
Fixes https://github.com/microsoft/kiota-python/issues/341
Updates std-uritemplate to latest version
> fix: fixes date-time in requests to align with std-uritemplate 2.0.0

- packages/abstractions/pyproject.toml
- packages/authentication/azure/pyproject.toml
- packages/bundle/pyproject.toml
- packages/http/httpx/pyproject.toml
- packages/serialization/form/pyproject.toml
- packages/serialization/json/pyproject.toml
- packages/serialization/multipart/pyproject.toml
- packages/serialization/text/pyproject.toml
- tests/validation/pyproject.toml
Signed-off-by: Vincent Biret <vibiret@microsoft.com>
> fix: outdated documentation links

- packages/serialization/form/pyproject.toml
- packages/serialization/json/pyproject.toml
- packages/serialization/multipart/pyproject.toml
> fix: bumps pendulum to a stable version

- .github/workflows/build.yml
- packages/abstractions/pyproject.toml
- packages/authentication/azure/pyproject.toml
- packages/bundle/pyproject.toml
- packages/http/httpx/pyproject.toml
- packages/serialization/form/pyproject.toml
- packages/serialization/json/pyproject.toml
- packages/serialization/multipart/pyproject.toml
- packages/serialization/text/pyproject.toml
- tests/validation/pyproject.toml
> feat: adds support for python 13
