microsoft/kiota-python

.github/workflows/build.yml
The tests are passing, but I think it's good to ensure the quality of contributions to always run the tests in CI.
=> Run the tests in CI

kiota_abstractions/request_option.py
The usage of RequestOptions in [kiota http](https://github.com/microsoft/kiota-http-python/blob/main/kiota_http/kiota_client_factory.py\#L101-L119) is of the signature of a staticmethod. This update ensures that the abstractmethod is exposed as an abstract and static method
https://github.com/microsoft/kiota-http-python/blob/0064ed6039f129039fb5e391e7aaa2d2f73d4ea4/kiota_http/kiota_client_factory.py#L101-L119
=> chore: use staticmethod decorator on get_key()

kiota_abstractions/request_option.py, kiota_abstractions/store/__init__.py, kiota_abstractions/store/backing_store.py, kiota_abstractions/store/backing_store_factory_singleton.py, kiota_abstractions/store/in_memory_backing_store.py, tests/authentication/test_api_key_authentication_provider.py, tests/conftest.py, tests/store/test_backing_store_factory_singleton.py
Ensure that the backing store factory that was set in the first instantiation of the class will be the default during run time.
This changes how the BackingStoreFactory is set [here](https://github.com/microsoft/kiota-http-python/blob/be3f79c61932eddf862519f58ed5d460d2648955/kiota_http/httpx_request_adapter.py#L265-L266):
```python
if backing_store_factory:
BackingStoreFactorySingleton.__instance = backing_store_factory # directly accessing an internal, protected member
if backing_store_factory:
BackingStoreFactorySingleton(backing_store_factory=backing_store_factory)
BackingStoreFactorySingleton(backing_store_factory=backing_store_factory)
```
I would like some more insight on why this has to be a singleton. This update changes the `BackingStoreFactorySingleton` API and I would love …
=> chore: update the BackingStoreFactorySingleton class

kiota_abstractions/api_error.py
Closes #133 
Try getting the 'error' attribute and return an empty string if it is not found.
=> Use `getattr` inbuilt with a default empty string

CHANGELOG.md, kiota_abstractions/_version.py, kiota_abstractions/request_information.py, tests/test_request_information.py
Preparation work for: https://github.com/microsoft/kiota/pull/3401
=> Add a try_add method for request headers

.github/workflows/publish.yml
Updates publish workflow to only trigger publishing on tags push
=> Trigger publishing only on tag

CHANGELOG.md, kiota_abstractions/_version.py, kiota_abstractions/base_request_configuration.py, tests/test_base_request_configuration.py
`DeprecationWarning` was being reported on import.
```
ImportError while loading conftest '/app/tests/conftest.py'.
tests/conftest.py:11: in <module>
from src.core.fastapi import get_application, get_router
src/core/fastapi.py:9: in <module>
from msgraph import GraphServiceClient
/usr/local/lib/python3.12/site-packages/msgraph/__init__.py:5: in <module>
from .graph_request_adapter import GraphRequestAdapter
/usr/local/lib/python3.12/site-packages/msgraph/graph_request_adapter.py:3: in <module>
from kiota_abstractions.authentication import AuthenticationProvider
/usr/local/lib/python3.12/site-packages/kiota_abstractions/authentication/__init__.py:3: in <module>
from .anonymous_authentication_provider import AnonymousAuthenticationProvider …
```
=> Fix deprication warning being reported on import

CHANGELOG.md, kiota_abstractions/_version.py, kiota_abstractions/request_information.py, tests/test_request_information.py
Fixes https://github.com/microsoft/kiota-abstractions-python/issues/245
Sanitizes types passed to the path/query object dictionaries to ensure success of various object types in the parameters. 
Adds tests to validate date,time,datetime,boolean,number and uuid types.
=> Adds path/query parameter sanization

packages/http/httpx/CHANGELOG.md, packages/http/httpx/kiota_http/httpx_request_adapter.py, packages/http/httpx/kiota_http/middleware/redirect_handler.py, packages/http/httpx/kiota_http/middleware/retry_handler.py, packages/http/httpx/kiota_http/middleware/url_replace_handler.py, packages/http/httpx/kiota_http/middleware/user_agent_handler.py, packages/http/httpx/tests/conftest.py, packages/http/httpx/tests/helpers/mock_async_transport.py, packages/http/httpx/tests/middleware_tests/test_base_middleware.py, packages/http/httpx/tests/middleware_tests/test_headers_inspection_handler.py, packages/http/httpx/tests/middleware_tests/test_parameters_name_decoding_handler.py, packages/http/httpx/tests/middleware_tests/test_redirect_handler.py, packages/http/httpx/tests/middleware_tests/test_retry_handler.py, packages/http/httpx/tests/test_httpx_request_adapter.py, packages/http/httpx/tests/test_kiota_client_factory.py
Sync sources for https://github.com/microsoft/kiota-http-python/pull/434 before moving to mono repo at https://github.com/microsoft/kiota-abstractions-python/pull/329
Validation of CI before merge at https://github.com/microsoft/kiota-abstractions-python/actions/runs/11324486373
=> sync sources for https://github.com/microsoft/kiota-http-python/pull/434

packages/abstractions/LICENSE, packages/abstractions/kiota_abstractions/serialization/serialization_writer.py, packages/abstractions/pyproject.toml, packages/authentication/azure/LICENSE, packages/authentication/azure/pyproject.toml, packages/http/httpx/LICENSE, packages/http/httpx/pyproject.toml, packages/serialization/form/LICENSE, packages/serialization/form/kiota_serialization_form/form_serialization_writer.py, packages/serialization/form/pyproject.toml, packages/serialization/json/LICENSE, packages/serialization/json/kiota_serialization_json/json_serialization_writer.py, packages/serialization/json/pyproject.toml, packages/serialization/multipart/LICENSE, packages/serialization/multipart/kiota_serialization_multipart/multipart_serialization_writer.py, packages/serialization/multipart/pyproject.toml, packages/serialization/text/LICENSE, packages/serialization/text/kiota_serialization_text/text_serialization_writer.py, packages/serialization/text/pyproject.toml, release-please-config.json
Closes https://github.com/microsoft/kiota-python/issues/372
This PR
- include licence file in distribution package.
- include group plugin to ensure versions are in sync
- Fixes typing issue discovered in https://github.com/microsoft/kiota/pull/5600
=> Fix releases

.github/workflows/publish.yml, release-please-config.json
Looks like according to https://github.com/googleapis/release-please/pull/1749 for the `linked-versions` plugin to align the versions, the component will need to be included in the tag. 
This will change the tag format in the repo from `v1.2.0` to be `microsoft-kiota-abstractions-v1.2.0` (therefore publishing a tag for each library similar to [kiota-typescript](https://github.com/microsoft/kiota-typescript/tags))
=> fix: ensure all packages are released together.

packages/serialization/json/kiota_serialization_json/json_serialization_writer.py, packages/serialization/json/tests/unit/test_json_serialization_writer.py
We currently have two issues:
1. We don't support `None` inside lists.
2. We convert `None` to `'null'` when there is no key. Simply fixing issue 1 would result in `['null', 'null']` instead of `[null, null]`.
The first issue arises when fetching, for example, all graph site pages of a site and attempting to serialize them. A specific case involves expanding `canvasLayout` and receiving a page without a `canvasLayout`, which results in `pinnedItems` containing `[None, None, None]`.
Although whether this response is correct is another question, the serialization should not raise an exception in this scenario but should handle it appropriately.
I have added relevant tests. Simply run `pytest` to verify the fix. Running the same tests without my changes will result in an exception.
=> correctly serialize None in a list

packages/abstractions/kiota_abstractions/serialization/parse_node_helper.py, packages/abstractions/kiota_abstractions/serialization/serialization_writer.py, packages/serialization/form/kiota_serialization_form/form_serialization_writer.py, packages/serialization/json/kiota_serialization_json/json_serialization_writer.py, packages/serialization/multipart/kiota_serialization_multipart/multipart_serialization_writer.py, packages/serialization/text/kiota_serialization_text/text_serialization_writer.py, tests/validation/pyproject.toml
Fixes errors related to https://github.com/microsoft/kiota/pull/5617
=> fix: fixes typing errors from integration tests for optional parameters

packages/abstractions/kiota_abstractions/request_adapter.py, packages/abstractions/kiota_abstractions/request_information.py, packages/abstractions/kiota_abstractions/serialization/parse_node.py, packages/http/httpx/kiota_http/httpx_request_adapter.py, packages/serialization/form/kiota_serialization_form/form_parse_node.py, packages/serialization/json/kiota_serialization_json/json_parse_node.py, packages/serialization/text/kiota_serialization_text/text_parse_node.py
Related to https://github.com/microsoft/kiota/pull/5729
Fixes failures in integration tests due to mypy failures in incorrect typing information for the following methods,
- `send_collection_of_primitive_async` from `RequestAdapter` should have the `type` as the parameter type for ResponseType
- Cleans up `set_content_from_parsable` to target parsable so that `set_content_from_scalar` can target scalars
- adds missing type info for `get_collection_of_primitive_values` as well as the derived implementations
- adds missing type info for `get_collection_of_object_values` as well as the derived implementations
=> fix: fixes typing issues discovered from github api generation

packages/abstractions/pyproject.toml, packages/authentication/azure/pyproject.toml, packages/bundle/pyproject.toml, packages/http/httpx/pyproject.toml, packages/serialization/form/pyproject.toml, packages/serialization/json/pyproject.toml, packages/serialization/multipart/pyproject.toml, packages/serialization/text/pyproject.toml
As the title says, `CHANGELOG.md` and `LICENSE` files are saving to the root `site-packages` dir. If you install all the serialization packages, these 2 files get overwritten a few times. Then when uninstalling (or running `poetry update` for that matter) you quickly run into `FileNotFoundError` errors and poetry telling you `Cannot install microsoft-kiota-serialization-text` or any of the other ones.
* **For license**, you don't even need to include it in the `include`, it gets detected automatically and is included within the package. ([here](https://github.com/python-poetry/poetry-core/blob/2cbe240beda1bb20eaf02a1ca0353b0ce6c167e6/src/poetry/core/masonry/builders/builder.py#L319-L327) are the files that get included automatically).
* **For changelog** you'd need to do [a clever hack …
=> Bugfix: CHANGELOG and LICENSE files are saving to the root site-packages dir

packages/http/httpx/kiota_http/middleware/retry_handler.py, packages/http/httpx/tests/middleware_tests/test_retry_handler.py
- Ensure calculated retry delay validated against correct maximum delay of 180 secs
-  Fixes retry handler exponential back-off to consider the delay specified in the retry handler option
- Ensures retry count is incremented based on value in retry-attempt header to prevent exceeding configured max retries
closes https://github.com/microsoft/kiota-python/issues/409
=> Fixes Retry Handler delay validation, retry count validation and exponential backoff

packages/http/httpx/kiota_http/httpx_request_adapter.py, packages/http/httpx/tests/test_httpx_request_adapter.py
Updates the regex extracting the base-64 encoded claims in the WWW-Authenticate header. More details provided in issue #420.
Fixes #420
=> fix: Regex extracting claims (addressing #420)

packages/http/httpx/kiota_http/httpx_request_adapter.py
Fixed the `opentelemetry` warning described in the corresponding github issue.
fixes #430 
N/A
N/A
* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output
=> fix: opentelemetry warning

.devcontainer/devcontainer.json, .vscode/settings.json, .vscode/tasks.json, CONTRIBUTING.md, requirements_dev.txt
Trying to make life easier for new contributors to this project by adding a dev container and additional docs Fixed Provide DevContainer with tests configured #453
Fixes #453
Integration with the test extension in VSCode still does not work, this would be an even better addition. Has to do with poetry and the test extension, that don't play nice together.
=> docs: DevContainer added and explained

packages/abstractions/kiota_abstractions/authentication/allowed_hosts_validator.py, packages/abstractions/tests/authentication/test_api_key_authentication_provider.py
Fixes #201
Add error handling for 'https://' and 'http://' prefixes in allowed host values.
* Modify `AllowedHostsValidator` class in `packages/abstractions/kiota_abstractions/authentication/allowed_hosts_validator.py` to throw a `ValueError` if any allowed host contains 'https://' or 'http://' prefix.
* Add a check in the `__init__` method and `set_allowed_hosts` method to throw a `ValueError` if any allowed host contains 'https://' or 'http://' prefix.
* Add tests in `packages/abstractions/tests/authentication/test_api_key_authentication_provider.py` to verify that a `ValueError` is thrown when 'https://' or 'http://' prefix is present in allowed host value.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/microsoft/kiota-python/pull/461 …
=> Throw error on `https://` and `http://` prefix if present in allowed host value

packages/http/httpx/kiota_http/httpx_request_adapter.py, packages/http/httpx/tests/test_httpx_request_adapter.py
Fixes #363
Add handling for 304 responses without a location header in request adapter.
* Modify `packages/http/httpx/kiota_http/httpx_request_adapter.py` to include a check for 304 status code in `_should_return_none` method.
* Return True if the status code is 304 and there is no location header.
* Add a unit test in `packages/http/httpx/tests/test_httpx_request_adapter.py` to verify that the request adapter returns null and does not throw for a 304 response without a location header.
* Create a mock 304 response without a location header.
* Ensure the unit test checks that the request adapter returns null for the 304 response.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/microsoft/kiota-python/pull/460?shareId=b8cffb0f-568e-4b4b-8a7 …
=> Ensure 304 status code does not throw, but returns None instead

packages/http/httpx/kiota_http/httpx_request_adapter.py
Previous implementation throws an exception which prevents customers from receiving the error payload for their failed response.
related IcM: https://portal.microsofticm.com/imp/v5/incidents/details/569882197/summary
=> fix: return error response if CAE claims are not present in WWW-Authenticate header

packages/serialization/json/kiota_serialization_json/json_parse_node.py, packages/serialization/json/tests/unit/test_json_parse_node.py
serialize objects to bytes in a JSON compatible way
Before, if an API returned an object which had been deserilised, and a library serialised it to bytes afterwards, that byte string would not be valid json as python's `str` serialises dictionaries with single quotes.
https://github.com/microsoftgraph/msgraph-sdk-python-core/issues/807
Optional. Screenshots, `curl` examples, etc.
Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.
* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output
=> serialize objects to bytes in a JSON compatible way

packages/http/httpx/kiota_http/middleware/retry_handler.py
The RetryHandler previously used `time.sleep(delay)` to pause between retries. However, `time.sleep` is a blocking call and can halt the entire async event loop, which negatively impacts asynchronous applications like FastAPI.
This PR replaces `time.sleep(delay)` with `await asyncio.sleep(delay)`, ensuring that the sleep is non-blocking and the event loop remains responsive during retry delays. This change improves compatibility and performance in asynchronous environments.
N.A
N.A
N.A
All existing Tests pass
=> fix: use asyncio.sleep for non-blocking delay in RetryHandler
